### ISSUE TITLE
自己紹介欄を更新しようとしたら500エラーが返り、以降自己紹介欄には `null` が入ってしまう

### ISSUE THREAD

**Issue by kachick** [Yasunori-aloha/lets-enjoy-hawaii#143]
<img width="546" alt="スクリーンショット 2021-02-22 3 19 19" src="https://user-images.githubusercontent.com/1180335/108634416-dae44a00-74bc-11eb-8886-214dd9d94eed.png">
<img width="815" alt="スクリーンショット 2021-02-22 3 19 27" src="https://user-images.githubusercontent.com/1180335/108634418-dcae0d80-74bc-11eb-80e0-a01103e50446.png">
<img width="842" alt="スクリーンショット 2021-02-22 3 19 41" src="https://user-images.githubusercontent.com/1180335/108634422-e0419480-74bc-11eb-890e-41b71a8ae4e2.png">

画像を添付せずに自己紹介欄を更新しようとしたらエラーになり、以降自己紹介欄には `null` が入ってしまうようです。

**Comment by kachick** [comment]
画像を添付しても同様にエラーになるみたいですね

**Comment by Yasunori-aloha** [comment]
ご指摘、ありがとうございます！
対応させていただきます！

**Comment by Yasunori-aloha** [comment]
お待たせいたしました。
ただいま、ご指摘のありました不具合を解消いたしました！

ユーザー情報更新等、正常に動作されることを再度ご確認ください。

**Comment by kachick** [comment]
<img width="1194" alt="スクリーンショット 2021-02-26 0 29 19" src="https://user-images.githubusercontent.com/1180335/109176058-c3150a80-77c9-11eb-91df-76a7d14ded36.png">

出来ました！早速のご対応ありがとうございます！
